### ISSUE TITLE
Better error handling for nullish results

### ISSUE THREAD

**Issue by vladinator1000** [jacksloan/prisma-proxy#4]
Sometimes when a query goes wrong I get an error that looks like
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Response.json (/home/vlady/code/yupty/api/node_modules/undici/lib/fetch/body.js:302:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Response.json (/home/vlady/code/yupty/api/node_modules/@miniflare/core/src/standards/http.ts:348:18)
    at UserModel.create (/home/vlady/code/yupty/api/server/db/models/User.ts:58:14)
```

This turned out to be because I was calling something like this, which returns `null`

```ts
prisma.user.findFirst({
    where: {
      email: 'nonexistent@email.com',
    },
})
```

Wonder if there is a way to better log errors to improve debugability? Or if we could do something to prevent `JSON.parse` being called on non-json results like this one?

**Comment by jacksloan** [comment]
[PR'd with some minor error handling improvements](https://github.com/jacksloan/prisma-proxy/pull/5)

Added handling for valid null-ish results in this PR.
Added a check for other JSON parse errors.
There's still a lot of room overall for improvements in error handling.
